#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################

github: [eliasdehondt, meastro85, vw03]
patreon: K10s
custom: ['https://www.patreon.com/K10s']