apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: example
spec:
  containers:
    - name: example-container
      image: nginx:latest
      ports:
        - containerPort: 80
