@base=http://localhost:8080

### GET NODES
GET {{base}}/nodes

### GET PODS
GET {{base}}/pods

### GET SERVICES
GET {{base}}/services

### GET CONFIGMAPS
GET {{base}}/configMaps

### GET SECRETS
GET {{base}}/secrets