@base=http://localhost:8080

### LOGIN
POST {{base}}/login
Content-Type: application/json

{
  "username": "scrat",
  "password": "password"
}

### GET NODES
GET {{base}}/secured/nodes

### GET PODS
GET {{base}}/secured/pods

### GET SERVICES
GET {{base}}/secured/services

### GET CONFIGMAPS
GET {{base}}/secured/configMaps

### GET SECRETS
GET {{base}}/secured/secrets

### GET DEPLOYMENTS
GET {{base}}/secured/deployments

### GET TABLE (Nodes)
GET {{base}}/secured/table?element=nodes

### GET TABLE (Pods)
GET {{base}}/secured/table?element=pODs&namespace=test

### GET STATS
GET {{base}}/secured/stats

### GET STATS FOR NODE
GET {{base}}/secured/stats?nodeName=node-1

### GET VISUALIZATION
GET {{base}}/secured/visualization