#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: k10s-namespaces
---