#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  username-to-lowercase:
    runs-on: ubuntu-latest
    outputs:
      LOWERCASE_USERNAME: ${{ steps.set-lowercase.outputs.LOWERCASE_USERNAME }}
    steps:
      - name: Set username to lowercase
        id: set-lowercase
        run: echo "::set-output name=LOWERCASE_USERNAME::$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')"

  build-backend:
    needs: [username-to-lowercase]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Backend Docker Image
        run: |
          docker build -t ghcr.io/${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }}/k10s-backend:latest ./App/Backend

  build-frontend:
    needs: [username-to-lowercase]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Frontend Docker Image
        run: |
          docker build -t ghcr.io/${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }}/k10s-frontend:latest ./App/Frontend

  push:
    needs: [build-backend, build-frontend, username-to-lowercase]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }} --password-stdin
      - name: Push Backend Docker Image
        run: |
          docker push ghcr.io/${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }}/k10s-backend:latest
      - name: Push Frontend Docker Image
        run: |
          docker push ghcr.io/${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }}/k10s-frontend:latest