#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################
name: Mirror GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror-github-to-gitlab-code:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-gitlab
      cancel-in-progress: true
    steps:
      - name: Clone repository
        run: git clone --bare "https://github.com/EliasDeHondt/K10s.git" .
      - name: Push to GitLab
        run: git push --mirror "https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/kdg-ti/the-lab/teams-24-25/k10s/k10s.git"