#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################
name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (optioneel)
        uses: actions/checkout@v4

      - name: Push to GitLab
        run: |
          git clone https://github.com/EliasDeHondt/k10s.git
          cd k10s
          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/EliasDeHondt/k10s.git