#################################
# @author K10s Open Source Team #
# @since 01/01/2025             #
#################################
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('App/backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Change to App/Backend directory
        run: cd App/Backend

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./testing/...